image: makeorg/docker-sbt

variables:
  SBT_OPTS: "-Xms1G -Xmx1G -XX:MaxMetaspaceSize=512M"

stages:
  - coverage
  - build

coverage:
  stage: coverage
  except:
    - tags
  tags:
    - docker
  before_script:
    - if [ ! -e /var/run/docker.sock ]; then DOCKER_DRIVER=vfs dockerd & fi
    - until docker ps; do echo "waiting for docker to be up..."; sleep 0.5; done
    - docker pull bouncestorage/swift-aio
  script:
    - sbt clean coverage test
    - sbt coverageReport

release:
  stage: build
  only:
    - tags
  except:
    - merge_requests
    - external_pull_requests
  before_script:
    - git fetch --tags
    - export TRAVIS_TAG=$CI_COMMIT_TAG
    - export GPG_TTY=$(tty)
    - echo "releasing version $CI_COMMIT_TAG"
    - echo $PGP_SECRET |base64 -d |gpg --import --batch
  script:
    - sbt ci-release
